spring:
  application:
    name: Kafka
  kafka:
    consumer:
      group-id: kafka
      auto-offset-reset: earliest
---
spring:
  profiles:
    active: cg2
  kafka:
    consumer:
      group-id: kafka2